local _Class = require("Base/base_class")
local _Singleton = require("Base/singleton_base")
local _PanelManager = require("Panel/panel_manager")
local _WindowManager = require("Window/window_manager")

_Singleton.Instance(_PanelManager):AddPanel("UI/Panel1","Panel1")
_Singleton.Instance(_PanelManager):AddPanel("UI/Panel2","Panel2")
_Singleton.Instance(_PanelManager):AddPanel("UI/Panel3","Panel3")
_Singleton.Instance(_PanelManager):ClickPanel()

_Singleton.Instance(_WindowManager):AddWindow("UI/win1","win1")
_Singleton.Instance(_WindowManager):AddWindow("UI/win2","win2")
_Singleton.Instance(_WindowManager):AddWindow("UI/win3","win3")
_Singleton.Instance(_WindowManager):ClickWindow()
_Singleton.Instance(_WindowManager):ClickBackBtn("UI/Back_btn")
_Singleton.Instance(_WindowManager):CloseWindow()